Fix missing using
Assets\Samples\PlaygroundSamples\Scripts\Module\BasicDashModule.cs(37,16): error CS0246: The type or namespace name 'EasingFunction' could not be found (are you missing a using directive or an assembly reference?)